export enum PropertiesActionType {
  PROPERTIES_LOADING = "PROPERTIES_LOADING",
  PROPERTIES_READY = "PROPERTIES_READY",
  CHANGE_BUDGET = "CHANGE_BUDGET",
  CHANGE_BATHROOMS = "CHANGE_BATHROOMS",
  CHANGE_ROOMS = "CHANGE_ROOMS",
  CHANGE_AREA = "CHANGE_AREA",
  CHANGE_PARKING = "CHANGE_PARKING",
}
